/*Generated by WaveMaker Studio*/

package com.testvcs1.mytestdatabase;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * Table2 generated by hbm2java
 */
@Entity
@Table(name="`TABLE2`"
    ,schema="MyTestDatabase"
)

public class Table2  implements java.io.Serializable {

    private Integer id;
    private Integer column2;
    private Table1 table1;

    public Table2() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`ID`", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    

    @Column(name="`COLUMN2`")
    public Integer getColumn2() {
        return this.column2;
    }
    
    public void setColumn2(Integer column2) {
        this.column2 = column2;
    }

    @Transient @OneToOne(fetch=FetchType.EAGER, mappedBy="table2")
    public Table1 getTable1() {
        return this.table1;
    }
    
    public void setTable1(Table1 table1) {
        this.table1 = table1;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof Table2) )
		    return false;

		 Table2 that = (Table2) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
    }


}

